<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="welcome-PC" name="RegisterTest" tests="1" failures="1" timestamp="12 Jun 2018 06:19:44 GMT" time="0.018" errors="0">
  <testcase name="registerTest" time="0.007" classname="testCases.RegisterTest">
    <failure type="java.lang.AssertionError" message="expected [xxxxxxx] but found [yyyyyyy]">
      <![CDATA[java.lang.AssertionError: expected [xxxxxxx] but found [yyyyyyy]
	at testCases.RegisterTest.registerTest(RegisterTest.java:13)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- registerTest -->
</testsuite> <!-- RegisterTest -->
